[package]
name = "smc-utils"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macsmc = "0.1.7"
clap = { version = "3.2.12", features = ["derive"] }
